project_id = "ffgkzvnbsdnfgmcxturx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"
buckets = []

[auth]
enabled = true
port = 54328
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_confirmations = false

[auth.external]
apple_enabled = false
azure_enabled = false
bitbucket_enabled = false
discord_enabled = false
facebook_enabled = false
github_enabled = false
gitlab_enabled = false
google_enabled = false
keycloak_enabled = false
linkedin_enabled = false
notion_enabled = false
spotify_enabled = false
slack_enabled = false
twitch_enabled = false
twitter_enabled = false
workos_enabled = false
zoom_enabled = false

[edge_runtime]
enabled = true
port = 54329

[functions.get-google-maps-key]
verify_jwt = true

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-restaurant-notification]
verify_jwt = false

[functions.send-weekly-digest]
verify_jwt = false

[functions.send-offer-alert]
verify_jwt = false

[functions.test-email-functions]
verify_jwt = false

[functions.send-waitlist-confirmation]
verify_jwt = false

[functions.ai-recommendations]
verify_jwt = false

[functions.cuizly-voice-chat]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.cuizly-voice-elevenlabs]
verify_jwt = false

[functions.voice-token-generator]
verify_jwt = false

[functions.voice-tools-handler]
verify_jwt = false

[functions.send-sms-verification]
verify_jwt = false

[functions.verify-sms-code]
verify_jwt = false