-- Update email templates with rich Cuizly design

-- Update auth config to use custom email templates with rich HTML design
UPDATE auth.config 
SET 
  external_email_enabled = true,
  external_email_confirm_signup_template = '{
    "subject": "Confirmez votre adresse email - Cuizly",
    "body": "<!DOCTYPE html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>Confirmation Cuizly</title></head><body style=\"margin:0;padding:0;background-color:#ffffff;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,sans-serif\"><div style=\"max-width:600px;margin:0 auto;padding:40px 20px\"><div style=\"text-align:center;margin-bottom:40px\"><img src=\"https://www.cuizly.ca/cuizly-logo.png\" width=\"120\" height=\"40\" alt=\"Cuizly\" style=\"margin:0 auto\"></div><h1 style=\"color:#171717;font-size:28px;font-weight:700;text-align:center;margin:0 0 30px 0;line-height:1.3\">Confirmez votre adresse email</h1><p style=\"color:#171717;font-size:16px;line-height:1.6;margin:0 0 20px 0\">Bonjour,</p><p style=\"color:#171717;font-size:16px;line-height:1.6;margin:0 0 20px 0\">Bienvenue sur Cuizly ! Pour finaliser votre inscription et découvrir les meilleures offres culinaires de Montréal, veuillez confirmer votre adresse email.</p><div style=\"text-align:center;margin:40px 0\"><a href=\"{{ .ConfirmationURL }}\" style=\"background-color:#171717;color:#ffffff;font-size:16px;font-weight:600;text-decoration:none;text-align:center;display:inline-block;padding:14px 32px;border-radius:50px;border:none;cursor:pointer\">Confirmer mon email</a></div><p style=\"color:#737373;font-size:14px;line-height:1.6;margin:20px 0 10px 0\">Si le bouton ne fonctionne pas, copiez et collez ce lien dans votre navigateur :</p><p style=\"color:#737373;font-size:12px;word-break:break-all;background-color:#f5f5f5;padding:10px;border-radius:8px;font-family:monospace\">{{ .ConfirmationURL }}</p><div style=\"background-color:#fafafa;padding:20px;border-radius:12px;margin:30px 0;border:1px solid #e5e5e5\"><p style=\"color:#525252;font-size:14px;line-height:1.6;margin:0\"><strong>Sécurité :</strong> Si vous n'\''avez pas créé ce compte, vous pouvez ignorer cet email en toute sécurité.</p></div><p style=\"color:#737373;font-size:14px;text-align:center;margin-top:40px;padding-top:20px;border-top:1px solid #e5e5e5\">L'\''équipe Cuizly<br><em>Ton prochain coup de cœur culinaire en un swipe.</em></p></div></body></html>",
    "redirect_to": "{{ .RedirectTo }}"
  }',
  external_email_reset_password_template = '{
    "subject": "Réinitialisation de votre mot de passe Cuizly", 
    "body": "<!DOCTYPE html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>Réinitialisation Cuizly</title></head><body style=\"margin:0;padding:0;background-color:#ffffff;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,sans-serif\"><div style=\"max-width:600px;margin:0 auto;padding:40px 20px\"><div style=\"text-align:center;margin-bottom:40px\"><img src=\"https://www.cuizly.ca/cuizly-logo.png\" width=\"120\" height=\"40\" alt=\"Cuizly\" style=\"margin:0 auto\"></div><h1 style=\"color:#171717;font-size:28px;font-weight:700;text-align:center;margin:0 0 30px 0;line-height:1.3\">Réinitialisation de mot de passe</h1><p style=\"color:#171717;font-size:16px;line-height:1.6;margin:0 0 20px 0\">Bonjour,</p><p style=\"color:#171717;font-size:16px;line-height:1.6;margin:0 0 20px 0\">Vous avez demandé la réinitialisation de votre mot de passe pour votre compte Cuizly.</p><p style=\"color:#171717;font-size:16px;line-height:1.6;margin:0 0 20px 0\">Cliquez sur le bouton ci-dessous pour créer un nouveau mot de passe. Ce lien est valide pendant <strong>24 heures</strong>.</p><div style=\"text-align:center;margin:40px 0\"><a href=\"{{ .ConfirmationURL }}\" style=\"background-color:#171717;color:#ffffff;font-size:16px;font-weight:600;text-decoration:none;text-align:center;display:inline-block;padding:14px 32px;border-radius:50px;border:none;cursor:pointer\">Réinitialiser mon mot de passe</a></div><p style=\"color:#737373;font-size:14px;line-height:1.6;margin:20px 0 10px 0\">Si le bouton ne fonctionne pas, copiez et collez ce lien dans votre navigateur :</p><p style=\"color:#737373;font-size:12px;word-break:break-all;background-color:#f5f5f5;padding:10px;border-radius:8px;font-family:monospace\">{{ .ConfirmationURL }}</p><div style=\"background-color:#fafafa;padding:20px;border-radius:12px;margin:30px 0;border:1px solid #e5e5e5\"><p style=\"color:#525252;font-size:14px;line-height:1.6;margin:0\"><strong>Sécurité :</strong> Si vous n'\''avez pas demandé cette réinitialisation, vous pouvez ignorer cet email en toute sécurité. Votre mot de passe actuel restera inchangé.</p></div><p style=\"color:#737373;font-size:14px;text-align:center;margin-top:40px;padding-top:20px;border-top:1px solid #e5e5e5\">L'\''équipe Cuizly<br><em>Ton prochain coup de cœur culinaire en un swipe.</em></p></div></body></html>",
    "redirect_to": "{{ .RedirectTo }}"
  }',
  external_email_magic_link_template = '{
    "subject": "Votre lien de connexion Cuizly",
    "body": "<!DOCTYPE html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>Connexion Cuizly</title></head><body style=\"margin:0;padding:0;background-color:#ffffff;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,sans-serif\"><div style=\"max-width:600px;margin:0 auto;padding:40px 20px\"><div style=\"text-align:center;margin-bottom:40px\"><img src=\"https://www.cuizly.ca/cuizly-logo.png\" width=\"120\" height=\"40\" alt=\"Cuizly\" style=\"margin:0 auto\"></div><h1 style=\"color:#171717;font-size:28px;font-weight:700;text-align:center;margin:0 0 30px 0;line-height:1.3\">Connexion sécurisée</h1><p style=\"color:#171717;font-size:16px;line-height:1.6;margin:0 0 20px 0\">Bonjour,</p><p style=\"color:#171717;font-size:16px;line-height:1.6;margin:0 0 20px 0\">Voici votre lien de connexion sécurisé pour accéder à votre compte Cuizly.</p><p style=\"color:#171717;font-size:16px;line-height:1.6;margin:0 0 20px 0\">Cliquez sur le bouton ci-dessous pour vous connecter instantanément. Ce lien est valide pendant <strong>1 heure</strong>.</p><div style=\"text-align:center;margin:40px 0\"><a href=\"{{ .ConfirmationURL }}\" style=\"background-color:#171717;color:#ffffff;font-size:16px;font-weight:600;text-decoration:none;text-align:center;display:inline-block;padding:14px 32px;border-radius:50px;border:none;cursor:pointer\">Me connecter</a></div><p style=\"color:#737373;font-size:14px;line-height:1.6;margin:20px 0 10px 0\">Si le bouton ne fonctionne pas, copiez et collez ce lien dans votre navigateur :</p><p style=\"color:#737373;font-size:12px;word-break:break-all;background-color:#f5f5f5;padding:10px;border-radius:8px;font-family:monospace\">{{ .ConfirmationURL }}</p><div style=\"background-color:#fafafa;padding:20px;border-radius:12px;margin:30px 0;border:1px solid #e5e5e5\"><p style=\"color:#525252;font-size:14px;line-height:1.6;margin:0\"><strong>Sécurité :</strong> Si vous n'\''avez pas demandé cette connexion, vous pouvez ignorer cet email en toute sécurité.</p></div><p style=\"color:#737373;font-size:14px;text-align:center;margin-top:40px;padding-top:20px;border-top:1px solid #e5e5e5\">L'\''équipe Cuizly<br><em>Ton prochain coup de cœur culinaire en un swipe.</em></p></div></body></html>",
    "redirect_to": "{{ .RedirectTo }}"
  }'
WHERE id = 1;